const langs = {
    "hu": {
        "close": "Bezárás",
        "download": "Letöltés",
        "screenshot": "Képernyőkép",
        "death": "Meghaltál",
        "eaten": "Megevett cuccok száma: ",
        "back": "Vissza a főoldalra",
        "respawn": "Újraéledés",
        "gamestopped": "Megállítva",
        "folytatas": "Folytatás",
        "documentation": "Dokumentáció",
        "mainmenu": "Kilépés",
        "droggopedia": "Droggopédia",
        "Pear": "Ez lenni jó, de enni nehez. Evés lenni 1mp, de poci lenni tele 3mp",
        "PearItem": "Körte",
        "Apple": "Alma. Én lenni boldog 5mpig",
        "AppleItem": "Alma",
        "Brokkoli": "Ez lenni rossz, lopni életemet",
        "BrokkoliItem": "Brokkoli",
        "Coin": "Oooooo, csilloooooog...",
        "CoinItem": "Csillógós cucc",
        "Brick": "Fogaim fájni, nem enni 5mpig",
        "BrickItem": "Tégla",
        "Shoe": "Nem fincsi... Én nem tudni futni mert én fulladozni 5mpig",
        "ShoeItem": "Cipő",
        "Backpack": "Én nem enni, de én zseb lenni nagy",
        "BackpackItem": "Tatyi",
        "Sign": "Ouuuuu, én nem látni jól 3 mpig, ez fájni...",
        "SignItem": "Tábla",
        "Drug": "Én tudni törni törvény, én tudni Xben sétálni, 5mp evés, de jó (30mpig)",
        "DrugItem": "X por",
        "Grass": "Nem bolti cucc, rossz. 10 mp evés, tenni gyorsá 10 mpig, aztán ölni",
        "GrassItem": "Fű",
        "Fuck": "AZTABÜDÖS ÉN LENNI ISTEN BASZOD ÉN URALNI MINDEN MUHAHAHAHAHAHAHAHAHA",
        "FuckItem": "cucc",
        "restart": "Újrakezdés"
    },
    "en": {
        "close": "Close",
        "download": "Download",
        "screenshot": "Screenshot",
        "death": "You have died",
        "eaten": "Number of stuff eaten: ",
        "back": "Back to the main page",
        "respawn": "Respawn",
        "gamestopped": "Game stopped",
        "folytatas": "Continue",
        "documentation": "Documentation",
        "mainmenu": "Exit",
        "droggopedia": "Droggopedia",
        "Pear": "Kinda yummy, hard to eat. Needs like 1 second to eat, but makes me tummy full for 3 seconds",
        "PearItem": "Pear",
        "Apple": "Apple. Me am happy for 5 seconds",
        "AppleItem": "Apple",
        "Brokkoli": "It bad, it steals me health",
        "BrokkoliItem": "Broccoli",
        "Coin": "Oooh, shiny...",
        "CoinItem": "Shiny stuff",
        "Brick": "It hurt me teeth, me no eat for 5 seconds",
        "BrickItem": "Brick",
        "Shoe": "Not yummy... Me choke so me can't run for 5 seconds",
        "ShoeItem": "Shoe",
        "Backpack": "Me no eat, but me pocket be big",
        "BackpackItem": "Backpack",
        "Sign": "Ouch, me cannot see for 3 seconds. It hurt...",
        "SignItem": "Sign",
        "Drug": "Me can break laws, me can walk in X, takes time to eat (5 seconds) but it good (for 30 seconds)",
        "DrugItem": "Powder X",
        "Grass": "Not from store, it bad, it takes 10 seconds to eat, it makes me fast for 10 seconds, then kills me",
        "GrassItem": "Grass",
        "Fuck": "OMFG ME AM DAS GOD ME CANNOT DIE ME RULE MUHAHAHAHA",
        "FuckItem": "stuff",
        "restart": "Restart"
    }
}